### PR TITLE
#160046067 Add Name Column To Approval Table 

### PR DESCRIPTION
**Pull request by clintfidel**
#### What does this PR do?
This PR ensures that requesters name appears on the approval table for seamless Identification

#### Description of Task to be completed?
- add requesters name to the approval table
- remove avatar from approval table

#### How should this be manually tested?
Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
Change into the project directory
Run the server using `make start`
Log in and click on My approvals to view requesters name column in the table

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#160046067](https://www.pivotaltracker.com/story/show/160046067)

#### Screenshots (if appropriate)
screen shot 2018-08-29 at 2 05 20 pm

#### Questions:

### CODE REVIEW

**Comment by Collins33** [comment]
Add the correct and updated way of running the application locally. You can check how it done from other pull requests.

**Comment by clintfidel** [comment]
@Collins33 I have addressed your comments on the PR

**Comment by seunzone** [comment]
looks good to me.

**Comment by Collins33** [comment]
The implementation of the table looks good. Although if you look at your commits, the last one, you have not written it in the right way. Give more context of the merge conflict, what caused the merge conflict and how you resolved it.

**Comment by clintfidel** [comment]
@collins33 and @hariclerry I have addressed all comments on PR, please kindly review and approve.

**Pull request merged**
