### PR TITLE
#161177585 Fix vacant spaces for guest house

### PR DESCRIPTION
**Pull request by ronaldndirangu**
#### What does this PR do?
This PR fixes the number of vacant spaces shown on the guest house details page. It was showing a hard-coded value but it should show the dynamic number of available spaces.

#### Description of Task to be completed?
- Filter rooms by faulty room.
- Filter vacant spaces by booked beds.

#### How should this be manually tested?
- Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- Enter into the project directory - `cd travel_tool_front`
- Install dependencies and start the  app - `make start`
-  [Start](https://github.com/andela/travel_tool_back/pull/139)  the backend.
- Navigate to [travela](http://travela-local.andela.com:3000) in your browser and login
- Go to the `DB` and on the `UserRoles` table, set yourself as a `Travel Admin`
- Go to the browser, refresh the page, Navigate to the `Residence` tab and  click on `Manage`
- You should view the available spaces in the `Available Spaces` card.
- Go the `DB` and set one room bed as booked is true to simulate that someone has booked it.
- The vacant spaces should reduce by one.
- You can also approve a travel request if you are logged in as a manager and the vacant spaces should change accordingly.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#161177585](https://www.pivotaltracker.com/story/show/161177585)

#### Screenshots (if appropriate)
screen shot 2018-10-30 at 10 33 03

#### Questions:
N/A

### CODE REVIEW

**Comment by ronaldndirangu** [comment]
@davenjeru it only updates when the request has been approved by the manager

**Comment by davenjeru** [comment]
> @davenjeru it only updates when the request has been approved by the manager

Take a look at this: https://cl.ly/06de6c4fb3ce

**Comment by ronaldndirangu** [comment]
@davenjeru Yeah the room is available today I think if you book on the same date that you view the vacant room that it might reflect. However, that is beyond the scope of this story, it can be raised as a bug if it fails. Try booking a room today which is the date reflected for the available rooms

**Comment by ronaldndirangu** [comment]
@davenjeru I have realized that it doesn't work. I had raised the question here https://andela.slack.com/archives/CBR2E13TJ/p1540811742077100 but it seems that maybe something changed without anyone realizing it and it needs to be fixed.

**Comment by ronaldndirangu** [comment]
@dmaish Thanks for the feedback. I have added the appropriate screenshot.

**Pull request merged**
