### PR TITLE
#159237221 Setup react router

### PR DESCRIPTION
**Pull request by hariclerry**
#### What does this PR do?
Setup react router for easy navigation. 

#### Description of Task to be completed?
 
1. Install and configure the router creating a dummy route for login and the "/" page to test the configuration
2.  Create components and views file structure where view pages are in
  the views folder but individual components are in the components folder

#### How should this be manually tested?

1. Run ```yarn start```  on the terminal
2. On the home page, click on the Login button to navigate to the Login Page

#### Any background context you want to provide?
By setting up react router, one is able to navigate between different components, changing the browser URL, modifying the browser history, and keeping the UI state in sync. Therefore, I created dummy pages to demonstrate how to navigate between different components.

#### What are the relevant pivotal tracker stories?

[#159237221](https://www.pivotaltracker.com/n/projects/2184887/stories/159237221)

#### Screenshots (if appropriate)

screen shot 2018-07-25 at 16 44 37

screen shot 2018-07-25 at 16 44 55

#### Questions:
N/A

### CODE REVIEW

**Comment by samuelkubai** [comment]
@hariclerry please update your branch with the develop branch.

**Comment by hariclerry** [comment]
@samuelkubai, I have rebased and my branch is up to date with develop.

**Comment by samuelkubai** [comment]
@hariclerry, for the structure of the components and views the folder name should be the same as the component file. E.g. Login >> Login.jsx || Login.scss

Please rename the folders and/or files accordingly.

**Comment by samuelkubai** [comment]
@hariclerry an extra task you can do while at that; add the .idea folder to the gitignore file for the people using Intellij Products (Webstorm, Phpstorm, etc)

**Comment by hariclerry** [comment]
@samuelkubai, am working on it. Thanks.

**Pull request merged**
