### PR TITLE
#160370620 Make multiple requests

### PR DESCRIPTION
**Pull request by seunzone**
#### What does this PR do?
This PR contains details for creating multiple requests by the user

#### Description of Task to be completed?
- A user should be able to see extra input fields when they click on multi-request
- A user should see new fields when they click on add another field
- Users should be able to post all request made to the the API
- Users should be able to delete input fields whilst making requests

#### How should this be manually tested?
- Clone this repo - `git clone https://github.com/andela/travel_tool_front.git`
- Switch to the repo directory - `cd travel_tool_front`
- Check out this branch - `git checkout ft-multitrip-modal-travel-request-160370620`
- Install dependencies and start the server  - `make start`
- Set up the server by following this [guide](https://github.com/andela/travel_tool_back/pull/46)
- Navigate to `localhost:3000` in a browser
- Create a new travel request
- From the Modal that appears, select `Multi City Trip`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#[160370620](https://www.pivotaltracker.com/story/show/160370620)

#### Screenshots (if appropriate)
screen shot 2018-09-15 at 2 58 20 pm

#### Questions:

### CODE REVIEW

**Comment by ezrqnkemboi** [comment]
My concept/thinking behind the multi-city trip is that you start from destination A to B, then to C henceforth and get back to destination A finally. 
In that case: 
-  When I fill in the details in the first step/trip, then the return should be the departure to the next destination and not return. 
- Also, the From field in the second trip(B), should be filled automatically and should be equal to Travel to in trip A, this will be the same in the case of the third trip, which equal to Travel to Field in trip B. 
- After finishing the three trips or all trips filled, then we can have a return date to the first destination. 
- This is a lot of work, but at first, it saves the work of typing(UX) and ensures a good flow of information to track. 
- This can be implemented in the next sprint due to the limit of time.

**Comment by samkubai** [comment]
@seunzone please name this the correct way.

**Comment by seunzone** [comment]
Thanks for your thought process @ezrqnkemboi we'll definitely look into this for the next sprint

**Comment by ezrqnkemboi** [comment]
Alright, @seunzone . We can definitely come with more better and better solutions for the system. Looking forward to making things better and better.

**Pull request closed without merging**
