### PR TITLE
#162573849 Add accommodation option

### PR DESCRIPTION
**Pull request by MuhanguziDavid**
#### What does this PR do?
 - Add accommodation option to one-way trips.

#### Description of Task to be completed?
 - Right now, a user booking a one-way trip is not able to select an accommodation option.
    This PR adds functionality to enable a user booking a one-way trip to be able to select an 
     accommodation option so they are not stranded in their new location.

##### Frontend
- Clone the repo
    `git clone https://github.com/andela/travel_tool_front.git`
 - Switch to the project directory
   `cd travel_tool_front`
 - Checkout the **ft-one-way-trip-accommodation-162573849** branch
   `git checkout ft-one-way-trip-accommodation-162573849`
 - Install dependencies and start the server
   - `make start` *if you have docker*
   - `yarn install` then `yarn start` *if you do not have docker*
 - Start the [backend](https://github.com/andela/travel_tool_back/pull/213) of this project. (Instructions below)
 - Navigate to [travela](http://travela-local.andela.com:3000/) in your browser and log in with your Andela account. 
 - Click on `New Request` and select `One Way Trip`.
 - Fill in the form and submit.
 - Your request should be added.

##### Backend
- Using your terminal, clone this repo -``` git clone https://github.com/andela/travel_tool_back.git```
- Change directory to the repo in your text editor-```cd travela_tool_back```
- Open the project in your text editor
- Checkout to this branch-```ft-one-way-trip-return-date-162573849```
- Run ```yarn install``` on your terminal
- Run ```yarn db:rollmigrate```
- Run ```yarn start:dev``` on your terminal to start the backend server

#### Any background context you want to provide?
 - The default arrival date has been set to one month after the departure date. This is because the `Available Rooms` can not be fetched without an arrival date.

#### What are the relevant pivotal tracker stories?
* [#162573849](https://www.pivotaltracker.com/story/show/162573849)

#### Screenshots (if appropriate)
one way accommodation

#### Questions:
N/A

### CODE REVIEW

**Comment by MuhanguziDavid** [comment]
Hi, @emekafredy , there is backend support for this PR. I have added it to `How to manually test this feature`

**Comment by MuhanguziDavid** [comment]
Thanks, @emekafredy , removing the asterisk from available rooms would affect all other trip options. I have left it there. However, I have ensured that a one-way trip cannot be created without choosing a room.

**Comment by MuhanguziDavid** [comment]
@Spectrumsun , You need backend support to run the task successfully. I added it on `How to manually test this feature` in the PR description.

**Comment by Spectrumsun** [comment]
@MuhanguziDavid my backend is running. Do you have a PR for the backend? your link takes me to just the backend develop

**Comment by MuhanguziDavid** [comment]
@Spectrumsun , yes I have a backend PR. Here is the link. `https://github.com/andela/travel_tool_back/pull/213`. I have also updated the link in my PR description.

**Pull request merged**
