### PR TITLE
#159236742 Setup redux

### PR DESCRIPTION
**Pull request by Collins33**
#### What does this PR do?
- It sets up redux as the state manager for the application.
- It adds a dummy action for adding requests and the store.

#### Description of Task to be completed?
- Install redux
- Setup the store
- Install the middleware
- Setup the reducer
- Setup file with action types
- Add a dummy action to add requests

#### How should this be manually tested?
-  Run ```yarn start```  on the terminal
- Go to the browser and open the console(F12)
**Use the following commands:**
- store.getState() to get the initial state
- store.dispatch( addRequest({ name: 'Travel to Nairobi', id: 1 }) ) to dispatch the dummy action to add the request
- store.getState() to get the current state after adding one request

#### Any background context you want to provide?
- The dummy action adds a request to the state.
- Testing the redux setup was done on the chrome console

#### What are the relevant pivotal tracker stories?
#159236742

#### Screenshots (if appropriate)
screen shot 2018-07-27 at 05 30 19

#### Questions:
NA

### CODE REVIEW

**Comment by samuelkubai** [comment]
@Collins33 you have configured redux properly, but we need to configure the sagas too because we are using redux sagas to interact with redux.

Go through this resource and understand how to make use of the sagas in redux-saga because as it stands now we are pulling in redux-saga but not using it anywhere.
Also for testing the configuration just create a counter element on the home page to test the configuration you can use the example the resource outlines as a guide on how to test both synchronous and asynchronous operations on the redux configurations.

**Comment by Collins33** [comment]
Alright. Let me implement everything.

**Comment by samuelkubai** [comment]
Here's a link to the resource.
https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html

**Comment by Collins33** [comment]
Thanks.

**Pull request merged**
