### PR TITLE
#159647999 Fix naming convention

### PR DESCRIPTION
**Pull request by Spectrumsun**
#### What does this PR do?
The pull request changes the names of the components and views to meet the best standards

#### Description of Task to be completed?
- Fix all the components and view naming to PascalCase

#### How should this be manually tested?
- Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- Change into the project directory
- Install project dependencies run `yarn install`
- Run the server `make start`
- To be able to login, add a supported domain name to your hosts:
  - `vim /etc/hosts` and add the line `127.0.0.1        local.andela.com`
- Open the browser and navigate to the Requests URL `http://local.andela.com:3000`
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
#159647999

#### Questions:
None

### CODE REVIEW

**Comment by samuelkubai** [comment]
@Spectrumsun also your PR title should start with a capital letter.

**Comment by Spectrumsun** [comment]
@samuelkubai PR Fix

**Comment by samuelkubai** [comment]
@Spectrumsun please resolve merge conflicts

**Comment by Spectrumsun** [comment]
@samuelkubai  conflict fixed

**Comment by samuelkubai** [comment]
@Spectrumsun add an appropriate label to this PR

**Comment by Spectrumsun** [comment]
@samuelkubai have add it

**Comment by Spectrumsun** [comment]
have fix the issues @samuelkubai

**Comment by Spectrumsun** [comment]
@samuelkubai PR fixed

**Comment by samuelkubai** [comment]
Archiving this PR in the meantime.

**Pull request closed without merging**
