### PR TITLE
#159392305 Create a Login Page

### PR DESCRIPTION
**Pull request by albert85**
#### What does this PR do?
Create a user interface login page

#### Description of Task to be completed?
- download video symbol into the images directory
- download the file symbol into the images directory
- download andela-logo symbol into the images directory
- Add button to the login page
- Add a road map image to the login page
- Add "how to book a trip" link to the login page
- Add "Andela travel policy" link to the login
- Add Andela logo and text to the login page
- Arrange all the task above to create a login page
- write a test that renders the login page inside the Login.test.js file

#### How should this be manually tested?
- Clone the repository
- Install all dependencies using `yarn install`
- Start the server using `yarn start`
- On the browser, navigate to `localhost:3000`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#159392305](https://www.pivotaltracker.com/story/show/159392305)

#### Screenshots (if appropriate)
login-page

#### Questions:
N/A

### CODE REVIEW

**Comment by hariclerry** [comment]
Code looks great so far except for the inconsistency in using quotes especially with imports, if we could just choose to use one type of quotes that would be great. i.e choose either double quotes or single quotes.

**Comment by hariclerry** [comment]
And why are the checks failing?

**Comment by Collins33** [comment]
The user interface looks good to me. My only issue is the failing checks for circleci and code climate. Is it possible for you to fix it?

**Comment by Collins33** [comment]
Previous changes seem to be implemented which is good but your test coverage seems to have dropped.

**Comment by hariclerry** [comment]
LGTM.

**Pull request merged**
