### PR TITLE
#160751476 Restyle toasts to match style guide

### PR DESCRIPTION
**Pull request by rovilay**
#### What does this PR do?
* it changes the toast styles

#### Description of Task to be completed?
* Change the toaster

#### How should this be manually tested?
* Clone this repo - `git clone https://github.com/andela/travel_tool_front.git`
* Change into the project directory
* Check out this branch with `git checkout ch-show-notification-toast-160751466`
* Start the server `make start`
* Setup the backend by following this [README.md](https://github.com/andela/travel_tool_front)
* In a browser, navigate to `localhost:3000`
* Perform an action that requires you to get a notification(create a request, approve a request)
* You should see the redesigned toaster

#### Any background context you want to provide?
* [Link To Toast Mock-up](https://projects.invisionapp.com/d/main/default/#/console/15027511/312473868/preview)

#### What are the relevant pivotal tracker stories?
* [#160751476](https://www.pivotaltracker.com/story/show/160751476)

#### Screenshots (if appropriate)
screen shot 2018-09-27 at 3 00 43 pm

#### Questions:
* N/A

### CODE REVIEW

**Comment by rovilay** [comment]
@ikenjoku Thanks for the feedback. It's been removed.

**Comment by albert85** [comment]
update the label of your PR to PEER_REVIEW

**Comment by rovilay** [comment]
@albert85 done.

**Comment by albert85** [comment]
@rovilay what about screenshot

**Comment by rovilay** [comment]
@albert85 Yes the styles are written in CSS and this is because I am just updating the styles of the `toastr` package. Changing the styles might interfere with the functionality of the toastr, because classnames might have been used in accessing the element to target functionalities.

**Pull request merged**
