### PR TITLE
#160370625 Edit posted comments

### PR DESCRIPTION
**Pull request by hariclerry**
#### What does this PR do?
This PR implements the edit comment functionality which enables users to edit own comment if errors were made in such comment.

#### Description of Task to be completed?
- Write tests for editing component and fix failing tests
- Create and implement the editing functionality for editing comments

#### How should this be manually tested?
- Clone the repository
- Run `make start` docker build command on the terminal to install all dependencies and run the App in the docker development environment server.
- On the browser, type the localhost URL ` http://localhost:3000` and Login with your Andela email account into the App.
- On the Requests page, click on the request Id from the list of requests displayed on the request table, you should be able to see the Request details Modal displayed.
- Add a new comment using the comment box.
- On the displayed added comment, click on the `edit` button to edit the comment.
- When done with editing and saving the changes, you should be able to see the edited comment displayed and labeled `edited`.

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#160370625](https://www.pivotaltracker.com/story/show/160370625)

#### Screenshots (if appropriate)

Screenshot showing newly added comments

screen shot 2018-09-18 at 23 32 40

Screenshot showing a comment being edited

screen shot 2018-09-18 at 23 33 20

Screenshot showing edited comment

screen shot 2018-09-18 at 23 34 41

#### Questions:
None

### CODE REVIEW

**Comment by johnmutuma5** [comment]
screen shot 2018-09-19 at 6 06 13 pm

**Comment by hariclerry** [comment]
@matthewacha, I am done with resolving the merge conflicts.

**Comment by johnmutuma5** [comment]
> Hey @johnmutuma5, I had not noticed that kind of behavior while adding new comments but nevertheless, the create comment functionality was not part of the scope of the task am working on but I will create a ticket as bug fix on that. Thanks for bringing that up.

Okay, @hariclerry, thanks for the response.

**Comment by johnmutuma5** [comment]
> Hey @johnmutuma5, I had not noticed that kind of behavior while adding new comments but nevertheless, the create comment functionality was not part of the scope of the task am working on but I will create a ticket as bug fix on that. Thanks for bringing that up.

Okay, @hariclerry, thanks for the response.

**Pull request merged**
