### PR TITLE
#162006704 Add responsiveness to requests modal

### PR DESCRIPTION
**Pull request by ronaldndirangu**
#### What does this PR do?
- This PR adds mobile responsiveness to the `New Request` Modal.

#### Description of Task to be completed?
- Add CSS styling to make the `New Request` Modal mobile responsive.

#### How should this be manually tested?
- Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- Enter into the project directory - `cd travel_tool_front`
- checkout the branch `git checkout ch-change-badge-for-approved-requests-161975169`
- Start the server with `make start`
- Start the backend of this project using this link [Click here](https://github.com/andela/travel_tool_back)
- Visit https://travela-local.andela.com
- Login to the application
- Navigate to the request page
- Create a new request.
- Change the size of the browser accordingly to simulate mobile devices resolutions.
- The modal should resize according to the display size.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#162006704](https://www.pivotaltracker.com/story/show/162006704)

#### Screenshots (if appropriate)
screen shot 2018-11-20 at 15 35 16
screen shot 2018-11-20 at 15 35 37

#### Questions:
N/A

### CODE REVIEW

**Comment by Spectrumsun** [comment]
can you look into making it responsive on large screen 
screenshot 2018-11-21 at 11 13 45 am 2

Also, it does not resize well on the moblie device @ronaldndirangu

**Comment by ronaldndirangu** [comment]
@Spectrumsun Thanks for the feedback. I had not thought of that. I have made the changes.

**Comment by Spectrumsun** [comment]
the date picker is not well formatted on small screen. it displays like this 
screenshot 2018-11-21 at 2 44 25 pm 2

Instead of like this
screenshot 2018-11-21 at 2 44 19 pm 2
 
Adding a Z index 0f 10 to the CSS property of the date picker would do the trick 
@ronaldndirangu

**Comment by Spectrumsun** [comment]
Nice Job @ronaldndirangu

**Pull request merged**
