### PR TITLE
#161374570 Dashboard Analytics

### PR DESCRIPTION
**Pull request by DennisWanjiru**
#### What does this PR do?
Implements trip requests analytics

#### Description of Task to be completed?
    - Create a reusable analytics card
    - Implement filtering by date range
    - Populate the cards with data from the API
    - Implement charts with real data from the API

#### How should this be manually tested?
- Clone the repo `https://github.com/andela/travel_tool_front.git`
- Checkout to the branch:
```ft-dashboard-analytics-161374570```
- Install dependencies:
```yarn install```
- Start the application:
```yarn start```

- Login to the application
- Navigate to the dashboard page on the sidebar
- You should be able to get results as shown in the screenshot below.

#### Any background context you want to provide?
1. To use the Dashboard - Create your standalone component and plug it into the dashboard component.
2. You should have the user role of a Travel Administrator or Super Administrator to be able to see the `manage` page. To do that:
  - Download `Postico` and connect to your travela database with relevant details: Db name, password, port, user
  - Click `userRoles` table and set the `roleId` to that of a Travel Administrator(29187) or Super Administrator(10948) 

#### What are the relevant pivotal tracker stories?
[161374570](https://www.pivotaltracker.com/story/show/161374570)

#### Screenshots (if appropriate)
ezgif com-crop 1

### CODE REVIEW

**Comment by samuelkubai** [comment]
@DennisWanjiru please update this title in accordance with the engineering playbook.

**Comment by samuelkubai** [comment]
@DennisWanjiru please attend to this PR.

**Comment by DennisWanjiru** [comment]
@samuelkubai On it

**Comment by DennisWanjiru** [comment]
@clintfidel  @Nedson202 @matthewacha There are a few tests I've not yet written you could review it for it to be merged. I will write the tests later as I have communicated with @samuelkubai. Thanks

**Comment by Nedson202** [comment]
Noted @DennisWanjiru

**Comment by Nedson202** [comment]
@DennisWanjiru please update the story ID in `What are the relevant pivotal tracker stories?

` section. The link takes me to a 404 on PT

**Comment by DennisWanjiru** [comment]
@Nedson202 Thanks for the heads up. I have fixed the issue.

**Comment by Nedson202** [comment]
I noticed that refreshing the `/dashboard` page redirects to `/requests`. Is there a fix for this one the way?  @DennisWanjiru

**Comment by DennisWanjiru** [comment]
@Nedson202 This is a problem I also encounter. The issue is in the checkCurrentUserRole  method doesn't work correctly

**Comment by Nedson202** [comment]
Working on resolving the conflicts right? @DennisWanjiru

**Comment by DennisWanjiru** [comment]
@Nedson202  I have resolved the merge conflicts and @clintfidel I have fixed the Card title. Thanks for the review

**Pull request merged**
