### PR TITLE
#160086204 Fix Request Dropdown

### PR DESCRIPTION
**Pull request by albert85**
#### What does this PR do?
It fixes request dropdown bug

#### Description of Task to be completed?
- change the anchor element under the render method into a div

#### How should this be manually tested?
- Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- Change into the project directory
- Run the server `make start`
- Login and click on request dropdown

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#160086204](https://www.pivotaltracker.com/story/show/160086204)

#### Screenshots (if appropriate)
screen shot 2018-08-28 at 1 17 39 pm
screen shot 2018-08-28 at 1 17 49 pm

#### Questions:
N/A

### CODE REVIEW

**Comment by johnmutuma5** [comment]
@albert85, congratulations on the dropdown bug. ___Well done!___

***A couple of issues:***
- I still have a problem with the page reloading all over again whenever I click on either `My Requests` or `My Approvals`. Once more, is this really the intended behavior? I believe it's not. cc @samuelkubai 
- New conflicting files

**Comment by samuelkubai** [comment]
@johnmutuma5 do you approve or request changes for this PR? Please be very clear about that.

**Comment by samuelkubai** [comment]
@albert85 this PR is slowly going stale. Please push that it's reviewed by everyone required.

**Comment by samuelkubai** [comment]
@albert85 the badge should be `ready` not completed.

cc. @daddychukz

**Comment by daddychukz** [comment]
looks good @samuelkubai

**Pull request merged**
