### PR TITLE
#160250660 Set height for landing page

### PR DESCRIPTION
**Pull request by seunzone**
#### What does this PR do?
Set height of landing page to match the viewport

#### Description of Task to be completed?
- Set height of landing page to match the viewport to look well both on desktop and mobile
- Open the Andela Travel Policy on a new button when the button is clicked. 

#### How should this be manually tested?
- Clone the repo - `git clone https://github.com/andela/travel_tool_front.git`
- Change into the project directory
- Run the server `make start`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#160250660](https://www.pivotaltracker.com/story/show/160250660)

#### Screenshots (if appropriate)
screen shot 2018-09-05 at 9 34 48 am
screen shot 2018-09-05 at 9 37 18 am

#### Questions:
N/A

### CODE REVIEW

**Comment by seunzone** [comment]
Thanks for pointing this out @clintfidel. Done

**Comment by clintfidel** [comment]
awesome @seunzone

**Comment by Collins33** [comment]
screen shot 2018-09-05 at 12 46 13
Should the space below the image be there?

**Comment by seunzone** [comment]
@Collins33 and @albert85 Thanks for pointing this out...Fixed

**Comment by seunzone** [comment]
screen shot 2018-09-05 at 11 31 27 am
screen shot 2018-09-05 at 11 30 09 am
@albert85 @amarachukwu-agbo 
It looks good now.

**Comment by samuelkubai** [comment]
@seunzone please fix the PR title.

**Pull request merged**
