### PR TITLE
#160141144 Update SideDrawer on mobile screen

### PR DESCRIPTION
**Pull request by Nedson202**
#### What does this PR do?
Replaces static data on sidedrawer to logged-in user information on mobile screen

#### Description of Task to be completed?
* Connect SideDrawer component to redux-store
* Retrieve logged-in user information
* Replace static data with information retrieved

#### How should this be manually tested?
* Clone the repo - git clone https://github.com/andela/travel_tool_front.git
* Change into the project directory
* Install project dependencies: yarn install
* Start app using make start
* Log in and change to mobile view
* Click the hamburger icon on the top-left, you'll see the logged-in 
user information as it is on larger screen

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#160141144](https://www.pivotaltracker.com/story/show/160141144)

#### Screenshots (if appropriate)
screen shot 2018-08-29 at 11 20 43 pm

#### Questions:

### CODE REVIEW

**Comment by Collins33** [comment]
Awesome work on the implementation of the task. It looks really good. One minor change. Remove the whitespace in the Sidedrawer.jsx file.

**Comment by Nedson202** [comment]
Thanks @Collins33 and @hariclerry. The issues pointed out will be resolved.

**Comment by Nedson202** [comment]
Hey @Collins33. Can you point out where the whitespace is?

**Comment by Collins33** [comment]
Looks good

**Comment by Nedson202** [comment]
The compiler error has been resolved @daddychukz

**Comment by daddychukz** [comment]
LGTM @samuelkubai

**Pull request merged**
