### PR TITLE
#162239807 Create content loaders on requests page

### PR DESCRIPTION
**Pull request by DennisWanjiru**
#### What does this PR do?
create data placeholders to represent the expected data appearance

#### Description of Task to be completed?
- Replace all the spinners on the requests, my verifications and my approvals with content placeholder loaders 

#### How should this be manually tested?
- Clone the repo `https://github.com/andela/travel_tool_front.git`
- Checkout to the branch:
`ft-requests-content-loaders-162239807`
- Install dependencies:
```yarn install```
`yarn test`
- All the tests should be passing
- Start the application:
```yarn start```

- Login to the application
- Navigate to the `my requests` or `my approvals` or `my verifications` page on the sidebar under `requests`
- You should be able to get results as shown in the screenshot below.

#### Any background context you want to provide?
- Create multiple requests so as to experience how the content loaders maps to the requests you have.

#### What are the relevant pivotal tracker stories?
[#162239807](https://www.pivotaltracker.com/story/show/162239807)

#### Screenshots (if appropriate)
ezgif com-crop 6

### CODE REVIEW

**Comment by samuelkubai** [comment]
@DennisWanjiru I would have expected that this PR cover the `My verifications` section too.

**Comment by DennisWanjiru** [comment]
@samuelkubai Its actually implemented given that am placing the placeholder on the HOC which wraps the 3 components

**Comment by samuelkubai** [comment]
@DennisWanjiru ooh, then it should be part of your PR description.

**Comment by DennisWanjiru** [comment]
@samuelkubai updated

**Comment by amarachukwu-agbo** [comment]
@DennisWanjiru, please resolve merge conflict

**Comment by DennisWanjiru** [comment]
@amarachukwu-agbo Done

**Comment by amarachukwu-agbo** [comment]
@DennisWanjiru when the verifications page is being reloaded from the link on the left side bar, the button group and the pagination header components still remain while the placeholder is displayed behind them. Please resolve this

**Comment by DennisWanjiru** [comment]
@amarachukwu-agbo I have fixed the said issue. Thanks

**Pull request merged**
