### PR TITLE
 #161962033 Fix request modal fields to match designs

### PR DESCRIPTION
**Pull request by ezrqnkemboi**
#### What does this PR do?

- Fix checkbox and multi-trip cancel icon designs in request modal
#### Description of Task to be completed?
- Fix checkbox request modal to match mockup
- Fix cancel icon in multi-trip request to match mockup

#### How should this be manually tested?
- Clone the repo - git clone https://github.com/andela/travel_tool_front.git
- Change into the project directory
- Run ```git checkout bg-fix-request-modal-design-161962033```
- Then Run ```yarn start```
- Click ```New request``` to popup new request modal
- Check the alignment of the send request and compare to the mocks 
- Check the cancel icon in multi-trip and compare it to the mocks
- Check alignment of personal details and remember my personal details and compare to the mockup
- Check on space between remember my personal details and travel details and compare to mockups

#### Any background context you want to provide?
[Request Form Mockup](https://projects.invisionapp.com/d/#/console/14861108/319652031/preview)
[Multi-trip cancel icon mockup](https://projects.invisionapp.com/d/#/console/14861108/319652029/preview)

#### What are the relevant pivotal tracker stories?
[#161962033](https://www.pivotaltracker.com/story/show/161962033)

#### Screenshots (if appropriate)

screen shot 2018-11-17 at 12 36 28

screen shot 2018-11-27 at 10 18 20

#### Questions:

### CODE REVIEW

**Comment by samuelkubai** [comment]
@ezrqnkemboi please resolve conflicts on this PR.

@amarachukwu-agbo any headway on reviewing this PR.

**Comment by amarachukwu-agbo** [comment]
@samuelkubai , yes, some changes were to be made. Will confirm if everything is fine now before proceeding to merge

**Comment by amarachukwu-agbo** [comment]
@ezrqnkemboi , the `Add a new trip div` is still not clickable as we discussed and the cancel icon is not aligned properly. Also the buttons are not aligned to the left of the form(this was fixed today, ensure you rebase off develop)
screenshot 2018-11-23 at 6 04 55 pm

**Comment by ezrqnkemboi** [comment]
I am working on fixing the issues. Thank you.

**Pull request merged**
