### PR TITLE
#161596122 Delete document

### PR DESCRIPTION
**Pull request by Nedson202**
#### What does this PR do?
Enables a user to delete a document

#### Description of Task to be completed?
- Create a confirmation dialog
- Create action, reducer, and saga for document deletion
- Write tests for implementation

#### How should this be manually tested?
- Clone the repo - git clone https://github.com/andela/travel_tool_front.git
- Enter into the project directory - cd travel_tool_front
- Install dependencies and start the server - make start
- Start the backend - git clone https://github.com/andela/travel_tool_front.git && make start
- Navigate to travela in your browser and login into the app.
- Click on the Document tab
- Add a document if you don't have any existing document
- On a document row, click on the ellipses
- On the menu dropdown, select Delete
- A modal will pop up, click the delete button

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#161596122](https://www.pivotaltracker.com/story/show/161596122)

#### Screenshots (if appropriate)
del-doc

#### Questions:

### CODE REVIEW

**Comment by Nedson202** [comment]
Yea, working on resolving the conflicts.

**Comment by Nedson202** [comment]
@Spectrumsun conflicts have been resolved.

**Comment by Spectrumsun** [comment]
why is test coverage dropping in your branch @Nedson202

**Comment by Nedson202** [comment]
@Spectrumsun

**Comment by Spectrumsun** [comment]
please fix your conflict @Nedson202

**Comment by Spectrumsun** [comment]
Good Job @Nedson202

**Pull request merged**
